### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by seanrelay** [xmtp-labs/xmtp-inbox-web#205] opened 2023-04-20 19:22 UTC
### Is your feature request related to a problem?

Yes, I want to be able to share a link for people to message me on xmtp.chat

### Describe the solution to the problem

Let me share a URL such as http://xmtp.ch/dm/0xaddress or xmtp.chat/dm/seanwbren.eth 
Anyone who follows that URL and enables XMTP will be already at the screen to send me a message

### Describe the uses cases for the feature

Lets people more easily share a link to connect with them, such as Twitter or LinkedIn does. 

### Additional details

The old version of xmtp chat had this feature (In ~January or so)

**Comment by neekolas** [comment] 2023-04-20 20:57
Closing as dupe of https://github.com/xmtp-labs/xmtp-inbox-web/issues/183, but we're on it

**Closed by neekolas** 2023-04-20 20:57 UTC
Labels: enhancement

**Comment by seanrelay** [comment] 2023-04-20 21:23
@neekolas would ENS name resolution be possible?

**Comment by neekolas** [comment] 2023-04-20 21:52
I believe it was already there at one point and got lost in a regression
