### ISSUE TITLE
Sent message doesn't display in convo until after I refresh

### ISSUE THREAD

**Issue by jhaaaa** [xmtp-labs/xmtp-inbox-web#260] opened 2023-05-09 23:14 UTC
**Describe the bug**
I type a message and tap send. The message disappears from the UI. I see push notifications from Orb that indicate the message was sent, but I don't see it in alpha.xmtp.chat until after I refresh the app. This happens sporadically. Sometimes it happens for sequential messages.

**To Reproduce**

1. Go to alpha.xmtp.chat
2. Type and send a few messages until a message doesn't display in the conversation.
3. Refresh the app. The missing messages display.

**Expected behavior**
A message I send displays in the convo immediately and without having to refresh the app.

**Device and browser:**
iPhone X, Chrome.

**Comment by jazzz** [comment] 2023-06-06 17:12
@jhaaaa are you still experiencing this behavior? I'm not able to reproduce it myself.

**Comment by jhaaaa** [comment] 2023-06-09 17:48
Thank you so much, @jazzz .... Just went in to verify and now I can't connect my wallet. When I tap **Connect your wallet**, nothing happens:

https://github.com/xmtp-labs/xmtp-inbox-web/assets/5481259/44a4a07c-8cf4-4604-b611-e3c7d2c45b2d

If I try it in incognito mode, I tap **Connect your wallet** and I do get the prompt to select my wallet. I pick MetaMask, but then it stays in MetaMask and doesn't take me back to alpha.xmtp.chat: 

https://github.com/xmtp-labs/xmtp-inbox-web/assets/5481259/bcb35a8a-18b8-47a3-bf1b-41d9560d0bc6

This is only in Chrome on my iPhone. alpha.xmtp.chat works fine for me in Chrome on my laptop. 

Any thoughts?

**Comment by yash-luna** [comment] 2023-06-09 21:08
Thank you for the details @jhaaaa. 

My gut says we backlog this since xmtp.chat is a webapp and we might have to spend time to make it fully functional and bug free for mobile. Especially with option to share Converse (and also the imminent wallet partner launch) with partners/users who prefer mobile.

Lastly, I've also heard the DX offsite hackathon idea of creating a RN example app which may serve mobile users/testers better than trying to optimize the webapp for mobile.

**Comment by rygine** [comment] 2023-10-05 14:09
@jhaaaa this issue should be fixed. please confirm when you get a chance.

**Comment by rygine** [comment] 2024-07-11 21:36
closing this issue as stale. please re-open if you're still having an issue.

**Closed by rygine** 2024-07-11 21:36 UTC
Labels: bug
